[package]
name = "snublejuice"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
mongodb = "3.4.1"
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["full"] }
tower-http = "0.6.8"
